source 'https://rubygems.org'
ruby '2.2.3'
gem 'database_cleaner'
gem 'data_mapper'
gem 'dm-postgres-adapter'
gem 'sinatra'
gem 'bcrypt'
group :test do
  gem 'shotgun'
  gem 'capybara'
  gem 'selenium-webdriver'
  gem 'rspec'
  gem 'pry'
  gem 'rake'
end
